# Generated by Django 5.1.5 on 2025-01-27 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('number_in_list', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('is_valid', models.BooleanField(default=False)),
                ('votes_needed', models.PositiveIntegerField()),
                ('votes_had', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
