# Generated by Django 5.1.5 on 2025-01-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_listitem_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='name',
            field=models.CharField(default='Unnamed Item', max_length=255),
        ),
    ]
