# Generated by Django 5.1.5 on 2025-02-03 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_listitem_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('valid', 'Valid'), ('not valid', 'Not Valid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_votes', to='webapp.listitem')),
            ],
            options={
                'unique_together': {('list_item', 'judge')},
            },
        ),
    ]
